-- AlterTable
ALTER TABLE `task` ADD COLUMN `category` ENUM('WORK', 'PERSONAL', 'ERRANDS', 'HEALTH', 'FINANCE', 'LEARNING', 'OTHER') NOT NULL DEFAULT 'OTHER',
    ADD COLUMN `importance` ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL DEFAULT 'MEDIUM',
    ADD COLUMN `priority` ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL DEFAULT 'MEDIUM';
